// export reducer event home
export const REQUEST_GET_EVENTS = 'REQUEST_GET_EVENTS';
export const REQUEST_LOADING = 'REQUEST_LOADING';
export const REQUEST_REJECTED = 'REQUEST_REJECTED';
export const REQUEST_ADD_EVENT = 'REQUEST_ADD_EVENT';
export const REQUEST_DELETE_EVENT = 'REQUEST_DELETE_EVENT';
export const REQUEST_UPDATE_EVENT = 'REQUEST_UPDATE_EVENT';
export const REQUEST_FILTER_EVENT_ROOM = 'REQUEST_FILTER_EVENT_ROOM';
export const REQUEST_DISTICNT_EVENT = 'REQUEST_DISTICNT_EVENT';
export const REQUEST_DELETE_EVENT_EXCEPTION = 'REQUEST_DELETE_EVENT_EXCEPTION';
export const REQUEST_EDIT_EVENT_EXCEPTION = 'REQUEST_EDIT_EVENT_EXCEPTION';
// export reducer rooms admin
export const REQUEST_GET_ROOMS = "REQUEST_GET_ROOMS";
export const REQUEST_DELETE_ROOM = "REQUEST_DELETE_ROOM";
export const REQUEST_ADD_ROOM = "REQUEST_ADD_ROOM";
export const REQUEST_UPDATE_ROOM = "REQUEST_UPDATE_ROOM";
// export reducer rooms book room
export const REQUEST_GET_BOOKROOM = "REQUEST_GET_BOOKROOM";
export const REQUEST_DELETE_BOOKROOM = "REQUEST_DELETE_BOOKROOM";
export const REQUEST_ADD_BOOKROOM = "REQUEST_ADD_BOOKROOM";
export const REQUEST_UPDATE_BOOKROOM = "REQUEST_UPDATE_BOOKROOM";
// export reducer login 
export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const REQUEST_LOGOUT = "REQUEST_LOGOUT";
export const REQUEST_CHECK_LOGIN = "REQUEST_CHECK_LOGIN";
// export research
export const REQUEST_RESEARCH = "REQUEST_RESEARCH";
//export user
export const REQUEST_GET_USERS = "REQUEST_GET_USERS";